### PR TITLE
Fix onTyping detection

### PR DESCRIPTION
**Pull request by 2FWAH**
FB changed the format of typing notification messages:
- update "mtype" from "typ" to "ttyp".
- Get thread ID from "to" to "thread_fbid" ("thread" looks the same)

### CODE REVIEW

**Comment by madsmtm** [comment]
I looked at it a bit, and you're partially right, though I found that `mtype` is set to `typ` when its a user thread, and `ttyp` when it's a group thread.

Apart from that, the `to` parameter were incorrectly used as `thread_id` before for user chats anyway, because when it's a user chat you would expect `thread_id` to be the other person's ID, but `to` would be your own ID.

**Comment by 2FWAH** [comment]
I fixed my PR to call onTyping for both "typ" and "ttyp".

**Comment by madsmtm** [comment]
I realised that I couldn't properly explain the issue, so I just went ahead and fixed it. `thread_fbid` is only available to group threads, but on user threads, `to` is still wrong to use, since it simply points to yourself. There (unless you're the person sending the typing status) `author_id` would be the correct user thread, too.

**Comment by madsmtm** [comment]
I realised that I couldn't properly explain the issue, so I just went ahead and fixed it. `thread_fbid` is only available to group threads, but on user threads, `to` is still wrong to use, since it simply points to yourself. There (unless you're the person sending the typing status) `author_id` would be the correct user thread, too.

**Pull request merged**
