### PR TITLE
Added heart reaction

### PR DESCRIPTION
**Pull request by kugo12**

### CODE REVIEW

**Comment by madsmtm** [comment]
I've verified that this works while listening for messages, when fetching messages and when reacting to messages.

Thanks 👍

**Comment by nikatark** [comment]
how do i  install / add this to my messenger ? sorry new to github.

**Comment by ekohilas** [comment]
@nikatark What are you trying to acomplish?
This module is meant to emulate what messenger does in the background, so it wouldn't make much sense to "install" it into messenger.

**Comment by nikatark** [comment]
i wanted to get the heart emoji reaction , some people even have the + icon allowing them to use any emoji as a reaction so i was trying to get that.

**Comment by madsmtm** [comment]
Hi there @nikatark. The functionality you're describing only works on mobile devices, as far as I can figure out, Facebook hasn't made a way that this can be done elsewhere.

**Pull request merged**
