### PR TITLE
Update client.py to post to groups (Issue #63)

### PR DESCRIPTION
**Pull request by aeantipov**
Jut followed the recipe in the issue

### CODE REVIEW

**Comment by SuperPichu** [comment]
Yes please merge this.

**Comment by Dgameman1** [comment]
But how do you actually use this to message a group?

**Comment by Dgameman1** [comment]
Works perfectly! Now, how do we get groups ID's automatically?

**Comment by aeantipov** [comment]
No idea in fact. So far I just picked a group chat and its id and sent a message there.

**Pull request merged**
