### PR TITLE
Fixes #126

### LINKED ISSUE #126: AssertionError: length must be positive integer, got 0
cant get the "Getting last messages sent" example work

`import fbchat

client = fbchat.Client("my fb ID", "pass")

friends = client.getUsers("my friend's name")
friend = friends[0]

last_messages = client.getThreadInfo(friend.uid,0)
last_messages.reverse()  # messages come in reversed order

for message in last_messages:
    print(message.body)
`
got this:

Logging in...

`<!DOCTYPE html><html lang="fr" id="facebook" class="no_js"><head><meta charset="utf-8" /
 (.....)
 a long html body 
 (.....)
/script>`
https://www.facebook.com/?seq=0&__req=3\n
Login successful
Traceback (most recent call last):
  File "fbchatExample.py", line 8, in <module>
    last_messages = client.getThreadInfo(friend.uid,0)
  File "C:\Program Files\python\2.7.13\lib\site-packages\fbchat\client.py", line
 583, in getThreadInfo
    assert last_n > 0, 'length must be positive integer, got %d' % last_n
AssertionError: length must be positive integer, got 0

D:\>

have already updated via pip and installed last version of python 2.7, 2.7.13

I have problem with the echobot example too,
 got this:

Login successful
Listening...
Received [{u'made': u'1492603113638', u'type': u'qprimer'}]
Received [{u'fbid': u'<my facebook ID>', u'type': u'deltaflow', u'sequencer': u'15944'}, {u'queue': <my facebook ID>L, u'ofd_ts': 1492603208789L, u'iseq': 15944, u'type': u'delta', u'delta': {u'irisSeqId': u'15944', u'actionTimestamp': u'1492603208646', u'watermarkTimestamp': u'1492600304313', u'class': u'MarkRead', u'threadKeys': [{u'otherUserFbId': u'<my friend's facebook ID>'}]}}]
Unknown type {u'fbid': u'<my facebook ID>', u'type': u'deltaflow', u'sequencer': u'15944'}
Received [{u'queue': <my facebook ID>L, u'ofd_ts': 1492603213397L, u'iseq': 15945, u'type': u'delta', u'delta': {u'folders': [u'FOLDER_INBOX'], u'irisSeqId': u'15945', u'class': u'MarkFolderSeen', u'timestamp': u'1492603223321'}}]
Received [{u'seen_timestamp': 1492603223321L, u'recent_unread': 2, u'unseen': 0, u'type': u'inbox', u'unread': 100, u'realtime_viewer_fbid': <my facebook ID>L}, {u'seen_timestamp': 1492603213000L, u'recent_unread': 2, u'unseen': 0, u'type': u'inbox', u'unread': 100, u'realtime_viewer_fbid': <my facebook ID>L}]
Received [{u'queue': <my facebook ID>L, u'ofd_ts': 1492603312379L, u'iseq': 15946, u'type': u'delta', u'delta': {u'body': u'**my sent message test**', u'irisSeqId': u'15946', u'class': u'NewMessage', u'attachments': [], u'messageMetadata': {u'tags': [u'source:titan:m_basic'], u'actorFbId': u'<my facebook ID>', u'messageId': u'mid.$cAAAABlV5Sghht1xg6lbhhcYDjwY_', u'offlineThreadingId': u'6260432042531423807', u'timestamp': u'1492603312362', u'threadKey': {u'otherUserFbId': u'<my friend's facebook ID>'}}}}]
**`<my facebook ID>` said: my sent message test**
Received [{u'queue': <my facebook ID>L, u'ofd_ts': 1492603316823L, u'iseq': 15947, u'type': u'delta', u'delta': {u'folders': [u'FOLDER_INBOX'], u'irisSeqId': u'15947', u'class': u'MarkFolderSeen', u'timestamp': u'1492603326743'}}]
Received [{u'seen_timestamp': 1492603326743L, u'recent_unread': 2, u'unseen': 0, u'type': u'inbox', u'unread': 100, u'realtime_viewer_fbid': <my facebook ID>L}, {u'seen_timestamp': 1492603317000L, u'recent_unread': 2, u'unseen': 0, u'type': u'inbox', u'unread': 100, u'realtime_viewer_fbid': <my facebook ID>L}]

I can see my sent message,
the message "my sent message test" is my sent message
but I dont know how to avoid these long debug log (if debug log they are, sorry Im have no big expertise in python yet)
when arrived, the response by the friend appears too.

I have combine these two problems in one issue because I think they are in relation..
any suggestions??

### PR DESCRIPTION
**Pull request by madsmtm**
Fixes #126 
Updated readme, and changed `getThreadInfo`, so `last_n` actually specifies the amount of retrieved messages

### CODE REVIEW

**Comment by carpedm20** [comment]
Yes the number should be bigger than 0. Thanks!

**Comment by carpedm20** [comment]
@madsmtm Hi. I think you have a great interest on project. Nowadays I am fully focused on machine learning research so if you are interested in being a Collaborator (getting push access to the repo) for this repo, feel free to tell me.

**Comment by madsmtm** [comment]
Hi @carpedm20. I do have great interest in this project ;). Being able to help out even more where I can would be lovely! Hope you enjoy your research!

**Comment by carpedm20** [comment]
@madsmtm Thanks! Thanks for the all contribution you did and I hope you enjoy this project.

**Pull request merged**
