### PR TITLE
Allowed empty login when session is given

### PR DESCRIPTION
**Pull request by ekohilas**
Changed login logic to allow empty login details when a session cookie is given.
A slight ease of use and security adjustment such that a password is not required when a session is given.

### CODE REVIEW

**Comment by madsmtm** [comment]
Well, couldn't you just input `None` manually when you don't want to store the password? I think the default case should be that you supply your credentials together with the session, since that will allow automatic login in if the session was invalid

**Comment by ekohilas** [comment]
Yeah I was thinking about that too... I guess I just like default arguments? :stuck_out_tongue: 

Would you be opposed to adding a login prompt if the login details are none when the session doesn't work?

**Comment by madsmtm** [comment]
Hmm, that'd break for people that are passing `None`s, but it'd be nice for newcomers. I'm not really sure, maybe make an issue about it, asking for other opinions? In any case, the login prompt should be customizable in an `on_` method

**Comment by madsmtm** [comment]
I'll hold off on this for now, I'd guess it's easier for newcomers when they're forced to supply login credentials.

And besides, logging in and loading from a session should ideally have been two different `classmethod`s.

**Pull request closed without merging**
